### ISSUE TITLE
[initial setup] - initial projeect setup

### ISSUE THREAD

**Issue by pitypec** [BuildForSDGCohort2/whatz-hot-frontend#12]
### Description

Initial project setup and implementation of typescript

### Resources

\<Additional Resources\>

### Acceptance Criteria

- [ ] 1. \<Outline of task which is a part of chore checklist\>
- [ ] 2. \<Outline of another task which is a part of chore checklist\>

**Comment by dave-ok** [comment]
Closed by #13
