### ISSUE TITLE
[feat] - user sign up page

### ISSUE THREAD

**Issue by pitypec** [BuildForSDGCohort2/whatz-hot-frontend#21]
### Narrative

As a &lt; user&gt;\
I want &lt; to be able to sign up on the platform&gt;\
so that &lt; i can access the platform&gt;

### Acceptance Criteria

- **Scenario**: Describe Scenario\
    Given &lt; email and password with first name and last name&gt;\
    ... And &lt; also alternatively using firebase auth&gt;...\
    When  &lt; you want to sign up&gt;\
    Then  &lt; sign up successfully&gt;\
    ... And &lt;another outcome&gt;...

**Comment by dave-ok** [comment]
Closed by #22
